function [Solution] = genSqSolRead(solLocName, A)
%[Solution] = genSqSolRead(solLocName, A)
%   
%   OUTPUT
%
%   Solution is a 6x6x9 matrix which indicates the placement of each
%   polyomino. The third entry is the index for the polyomino and the first
%   two are the rows and columns of the board respectively, starting from
%   the upperleftmost square.
%
%   
%   INPUTS
%
%   solLocName is the location of the .sol file generated by cplex which
%   has the solution to the binary matrix problem generated by
%   genSqProbGen, or whichever lp generator used.
%
%   A is the binary matrix which is used to generate the lp file in
%   genSqProb. It is the output A from the function ModeMat. It contains 
%   all of the possible positions of the polyominoes.
%
%
%   HOW IT WORKS
%
%   First, the function cplex_solution_read reads the binary solution from
%   the .sol file and stores that vector in x. 
%
%   k then finds the index of each of the ones in x. It is then used to
%   generate Sol, which is a 36x9 matrix that contains the data for all the
%   pieces in the solution.
%
%   Finally, the data in Sol is wrapped so that the matrices show what the
%   pieces should look like on the board.


x = cplex_solution_read(solLocName);

k = find(x);

Sol = A((1:36),k);

Solution = zeros(6,6,9);

for k = 1:9

j = 1:6;

for i = 1:6

    Solution(i,:,k) = Sol(j + ((i-1)*6),k);

end


end



end